### ISSUE TITLE
feat(runner-configuration): Allow GitLab runner concurrent job configuration

### ISSUE THREAD

**Issue by bobveringa** [neilkuan/cdk-gitlab-runner#1005]
It would be useful to configure the number of concurrent jobs a runner can handle. This means that it is not needed to create multiple runners if you are running many simple tasks (such as linting and waiting for servers to come online).

### Proposed Solution

Either a new configuration field is added to the GitlabContainerRunner construct like this
```javascript
const runner = new GitlabContainerRunner(this, 'testing', {
  gitlabtoken: '$GITLABTOKEN',
  ec2type: 't3.large',
  configuration: {
    concurrent_jobs: 4,
  }
});
```

or it is added as a new field

```javascript
const runner = new GitlabContainerRunner(this, 'testing', {
  gitlabtoken: '$GITLABTOKEN',
  ec2type: 't3.large',
  concurrent_jobs: 4,
});
```

### Links
* https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-global-section

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

It has been a while since I wrote JavaScript code, but I could try to implement this.

---

This is a :rocket: Feature Request

link this [issue](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1539#note_94267409) at gitlab

**Comment by bobveringa** [comment]
I've investigated this, and just adding in support for setting the number of concurrent jobs is fairly easy, but more advanced configuration would be a bit harder.

For just configuration, a line can be added to here https://github.com/neilkuan/cdk-gitlab-runner/blob/master/src/gitlab-runner-instance.ts#L596 That replaces the concurrent value in the TOML file.

Something like this:
```
`sed -i 's/concurrent = .*/concurrent = ${props.configuration.concurrent_jobs}/g' /home/ec2-user/.gitlab-runner/config.toml`
```

**Comment by neilkuan** [comment]
how about added OPTIONS `--request-concurrency` when register runner??

```bash
docker run -it --rm gitlab/gitlab-runner:alpine register --help | grep request-concurrency          
   --request-concurrency value                                                                Maximum concurrency for job requests (default: "0") [$RUNNER_REQUEST_CONCURRENCY]
```

**Comment by bobveringa** [comment]
Would you like to implement this yourself, or do you want me to implement it?

**Comment by neilkuan** [comment]
Hi @bobveringa, would you like to try  implement this ?? ;)

**Comment by bobveringa** [comment]
I would have to figure out how to get this to work within python, that might take some time. But I could take a look at this.

**Comment by bobveringa** [comment]
> how about added OPTIONS `--request-concurrency` when register runner??
> 
> ```shell
> docker run -it --rm gitlab/gitlab-runner:alpine register --help | grep request-concurrency          
>    --request-concurrency value                                                                Maximum concurrency for job requests (default: "0") [$RUNNER_REQUEST_CONCURRENCY]
> ```

Passing `--request-concurrency` did not appear to do anything. So, I went back to the solution I originally proposed. That does seem to update the concurrency setting.
