### ISSUE TITLE
registration-token deprecation

### ISSUE THREAD

**Issue by pgraemer** [neilkuan/cdk-gitlab-runner#1796]
gitlab deprecated the registration-token. 
for further reading check this:

https://docs.gitlab.com/ee/ci/runners/new_creation_workflow.html

**Comment by neilkuan** [comment]
Hi @pgraemer , Thanks for report this issue.
I already add new `gitlabRunnerVersion` props and helper function to resolve this issue at cdk-gitlab-runner@v2.2.0.
Cloud you try and give me a review ?! let me know what did you think. thank you.

**Comment by neilkuan** [comment]
> hey @neilkuan, just reviewed your changes and tested the latest version.
> 
> maybe one suggested change: considering the default `gitlabRunnerImage` is latest - why not set the `gitlabRunnerVersion` also to `latest` as a default?

because I didn't know what is `latest`( 16.1.0, 16.1.1 etc... ) version for `gitlabRunnerVersion`. lol

**Comment by pgraemer** [comment]
well i know that u cannot estimate the version of latest :D 

but the version check is now also somewhat ambiguous as you could also even set a specific flag like `useOldRegistrationFlow` to solve it. 

if i have time i try to propose a PR to showcase what i've meant :)
