### ISSUE TITLE
No longer possible to use SSM to store gitlab token

### ISSUE THREAD

**Issue by bobveringa** [neilkuan/cdk-gitlab-runner#1902]
**Describe the bug**
When using runner versions after 15.10, there is a check [here](https://github.com/neilkuan/cdk-gitlab-runner/blob/736b0af198353388408d53da614bc188344aab8a/src/gitlab-runner-instance.ts#L327) which checks if the token contains the substring 'glrt'. When fetching the token from SSM, you are given a token which is resolved deployment time. This token does not contain `glrt` which stops the execution

**To Reproduce**
```python
gitlab_token = ssm.StringParameter.from_string_parameter_name(
    self, 'gitlabRunnerRegisterToken',
    string_parameter_name='/gitlab/groupToken',
)

runner = GitlabContainerRunner(
    self, 'gitlabRunner',
    gitlabtoken=gitlab_token.string_value,
    gitlab_runner_version='16.8',
    ec2type='t3.small',
    concurrent_jobs=3,
    tags=[],
    runner_description='Group Runner',
)
```

**Additional context**
I am using python.

**Comment by bobveringa** [comment]
Found a workaround that can be used, but it is not optimal.

The `glrt-` part of the token can be removed in SSM. The following construction can then be used to satisfy the check and still store (most of) the token in SSM.

```python
gitlab_token = ssm.StringParameter.from_string_parameter_name(
    self, 'gitlabRunnerRegisterToken',
    string_parameter_name='/gitlab/groupToken',
)

gitlab_token = f'glrt-{gitlab_token.string_value}'
```

A proper solution would still be desired. Maybe even more native support for SSM and SecretManager params?

**Comment by neilkuan** [comment]
Thank you for report this issue, I will take a look.
