### ISSUE TITLE
(feat): Multiple GitLab CI tokens

### ISSUE THREAD

**Issue by Obirah** [neilkuan/cdk-gitlab-runner#398]
I would love to see this construct library being able to handle multiple GitLab CI tokens for one runner.

### Use Case

Creating a runner that is supposed to cover multiple projects but not a whole group.

### Proposed Solution

This...
```
new GitlabRunnerAutoscaling(stack, 'foo', {
  gitlabToken: 'bar'
});
```

...becomes this:
```
new GitlabRunnerAutoscaling(stack, 'foo', {
  gitlabTokens: ['bar', 'baz']
});
```

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by neilkuan** [comment]
Hi @Obirah , I think maybe become to this will been well.
```ts
new GitlabRunnerAutoscaling(stack, 'foo', {
  runners: [
  {
     gitlabTokens: 'foo',
     tags: ['a', 'dev'],
     dockerVolumes: [{
      hostPath: '/tmp/cahce',
      containerPath: '/tmp/cahce',
    }],
}, {
     gitlabTokens: 'bar',
     tags: ['b', 'dev'],
     ...
}
  ],
});
```
wdyt @gotodeploy

**Comment by gotodeploy** [comment]
@neilkuan I think what @Obirah needs is just one runner for multiple projects rather than multiple runners for multiple projects. Probably registering multiple tokens via `gitlab register` command at once is impossible. So we should have a feature to edit [config.toml](https://docs.gitlab.com/runner/register/#runners-configuration-template-file).

**Comment by neilkuan** [comment]
@Obirah , what do you think ?!

**Comment by Obirah** [comment]
@neilkuan the scenario that @gotodeploy described is exactly what I need. 👍🏻

**Comment by gotodeploy** [comment]
@Obirah Have you started implementing this feature by yourself?

**Comment by Obirah** [comment]
> @Obirah Have you started implementing this feature by yourself?
> 
> P.S. @neilkuan FYI: https://forum.gitlab.com/t/run-runners-in-parallel-on-the-same-server/9213/3
Nope, unfortunately I will not have time for that in the next weeks. :/ But I'll keep it in the back of my head and look back into it if the issue stays open.
